name: yanapay_app_mobile
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  http: ^1.4.0
  path: any
  mime: any
  http_parser: any
  flutter_dotenv: ^5.2.1
  go_router: ^15.1.3
  permission_handler: ^12.0.0+1
  image_picker: ^1.1.2

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.2.19
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"

flutter_native_splash:
  color: "#A1D35D"
  image: assets/images/logo.png
  android: true
  ios: true



flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/logo.png
